server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

service:
  poke-api:
    url: https://pokeapi.co/api/v2/
    berry-service:
      berries: berry/
      berry-firmness: berry-firmness/
      berry-flavor: berry-flavor/
    pokemon-service:
      pokemon: pokemon/
    evolution-service:
      chain: evolution-chain/
